#!/bin/bash
# run this once you're in the chroot
# shortened RAW URL: https://goo.gl/ZTNeQt
# genfstab -U /mnt >> /mnt/etc/fstab
# arch-chroot /mnt /bin/bash

echo "Enter the target hostname..."
read HOSTNAME
echo "Enter the main user (usually kolbasz)..."
read USER
echo "GRUB will install to /dev/sda, edit if needed"
sleep 10s
echo "wait 10s"

echo "Hostname:               '$HOSTNAME'"
echo "Username:               '$USER'"
#echo "systemd-boot partition: '/dev/$PARTITION'"
echo ""
echo ""

### Doing actual stuff
echo en_US.UTF-8 UTF-8 > /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8
ln -s /usr/share/zoneinfo/America/New_York /etc/localtime
hwclock --systohc --utc
echo $HOSTNAME > /etc/hostname

# packages
cat <<EOT >> /etc/pacman.conf
[multilib]
Include = /etc/pacman.d/mirrorlist

[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/\$arch
EOT

pacman -Syu \
  arandr \
  ansible \
  audacity \
  bash-completion \
  bridge-utils \
  btrfs-progs \
  chromium \
  curl \
  deja-dup \
  docker \
  firefox \
  git \
  gnome \
  gnome-tweak-tool \
  grub \
  hddtemp \
  htop \
  iftop \
  intel-ucode \
  iotop \
  lame \
  lib32-nvidia-340xx-libgl \
  libvirt \
  lm_sensors \
  lsof \
  mc \
  mesa \
  mumble \
  ncdu \
  networkmanager \
  nmap \
  ntp \
  numix-themes \
  nvidia-340xx \
  nvidia-340xx-libgl \
  nvidia-settings \
  openssh \
  openttd \
  openttd-opengfx \
  powertop \
  qemu \
  quassel-client \
  reptyr \
  rsnapshot \
  samba \
  screen \
  skype-call-recorder \
  sl \
  smbclient \
  steam \
  strace \
  sudo \
  synergy \
  teamspeak3 \
  tmux \
  tree \
  vagrant \
  vim \
  virt-manager \
  virtualbox \
  virtualbox-guest-iso \
  virtualbox-host-modules \
  vorbis-tools \
  wget \
  which \
  xorg-server \
  xorg-server-devel \
  xorg-server-utils \
  xorg-twm \
  xorg-xclock \
  xorg-xinit \
  xorg-xrandr \
  xterm \
  yaourt \
  youtube-dl

# add user
useradd -m -g users -s /bin/bash $USER
usermod -aG wheel $USER
usermod -aG docker $USER

# set default passwords to 22
echo "root:22" | chpasswd
echo "$USER:22" | chpasswd

# enable services
systemctl enable sshd
systemctl enable gdm
systemctl enable NetworkManager
systemctl enable docker
systemctl enable ntpd

# Grub install
grub-install --target=i386-pc /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

# git setup
echo "Configuring git..."
git config --global user.email "kolbaszkarcsi@gmail.com"
git config --global user.name "kolbasz12"
git config --global push.default simple

# configure X
echo "Configuring X..."
nvidia-xconfig
cp /etc/X11/xorg.conf /etc/X11/xorg.conf.d/20-nvidia.conf

# initramfs
mkinitcpio -p linux

# rank pacman mirrors
# echo "Ranking mirrors... Takes 5-10 minutes."
# cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
# sed '/^#S/ s|#||' -i /etc/pacman.d/mirrorlist.backup
# rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist

# more scripts, post install
cd /opt 
curl -LO https://raw.githubusercontent.com/Kolbasz12/arch/master/systems/post-install
# curl -LO https://raw.githubusercontent.com/IronicBadger/arch/master/install/vfio.sh

echo ""
echo "All done. Just add your modules to mkinitcpio.conf"

